config/routes.rb
Filer::Application.routes.draw do

  resources :clusters
  resources :filespaces
  resources :users
  resources :folders do
    resources :documents
    resources :uploads
  end
  
  root :to => 'clusters#index'

end

app/models/filespace.rb
class Filespace < ActiveRecord::Base
  attr_accessible :name
  has_many :folders
  belongs_to :root_folder, class_name: Folder
  belongs_to :current_folder, class_name: Folder
  belongs_to :incoming_folder, class_name: Folder
  belongs_to :trash_folder, class_name: Folder
  belongs_to :archived_folder, class_name: Folder
  
  has_many :clusterings
  has_many :clusters, through: :clusterings
   
  validates_presence_of :name
  
  class Error < StandardError; end
  
  #
  # Create a snapshot of the current filespace.  The current version
  # number is copied into the snapshot filespace, and the version
  # number of the current filespace is then incremented.
  #
  def snapshot!
    opts = {
      uuid: uuid,
      version: version,
      name: name,
      snapshot: true,
      latest: false
    }
    raise Error, "Can only snapshot latest version" unless latest
    fs = nil
    ActiveRecord::Base.transaction do
      fs = self.class.generate!(opts)
      fs.current_folder = 
        self.current_folder.copy!(fs.root_folder, recursive: true)
      fs.archived_folder = 
        self.archived_folder.copy!(fs.root_folder, recursive: true)
      fs.save!
      self.version += 1
      save!
    end
    fs
  end
  
  def total_folders
    Filespace.where(filespace_id: self.id).all.size
  end

  # Set up a new filespace.
  def self.generate!(opts = {})
    ActiveRecord::Base.transaction do
      filespace = Filespace.create!(name: opts[:name])
      filespace.uuid = opts[:uuid] || `uuidgen`.strip
      filespace.version = opts[:version] || 1
      filespace.latest = opts.has_key?(:latest) ? opts[:latest] : true
      root = filespace.folders.build(name: "Root")
      root.leaf = false
      filespace.folders << root
      filespace.root_folder = root
      folders_to_create = ["incoming", "trash"]
      folders_to_create |= ["current", "archived"] unless opts[:snapshot]
      folders_to_create.each do |ntype|
        f = filespace.folders.build(name: ntype.titleize)
        f.ntype = ntype
        root.children << f
        filespace.send("#{ntype}_folder=", f)
      end
      filespace.save!
      filespace
    end
  end
end

app/controllers/filespaces_controller.rb
class FilespacesController < ApplicationController
   
  def index
    @filespaces = Filespace.all
  end

  def show
    @filespace = Filespace.find(params[:id])
  end

  def new
    @filespace = Filespace.new
  end

  def create
    @filespace = Filespace.generate!(params[:filespace])
  rescue
    render :action => 'new'
  else
    flash[:notice] = "Successfully created filespace."
    redirect_to @filespace
  end

  def edit
    @filespace = Filespace.find(params[:id])
  end
  
  def update
    @filespace = Filespace.find(params[:id])
    if @filespace.update_attributes(params[:filespace])
      flash[:notice] = "Successfully updated filespace."
      redirect_to filespace_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @filespace = Filespace.find(params[:id])
    @filespace.destroy
    flash[:notice] = "Successfully destroyed filespace."
    redirect_to filespaces_url
  end

end

app/helpers/filespaces_helper.rb
module FilespacesHelper
end

app/views/filespaces/_filespace.html.erb
<div id="filespace-<%= id %>" data-filespace="<%= id %>"
  data-root-folder="<%= root %>" data-current-folder="<%= current %>"
  class="filespace-panel">

      <div class="tree-wrapper">
          <div class="liner">
              <div class="explanation">
                  Click on a folder to select it.  Then click
                  <em>View Files</em> to view the files in the folder, or
                  click <em>Upload Files</em> to upload files to the folder.
              </div>
              <%= tag("div", {id: "node-#{root}", "class" => "filespace-tree",
                "data" => {"filespace" => id, "root-folder" => root,
                "current-folder" => current}}, true) %>
              </div>
          </div>
      </div>

    <div class="table-wrapper"> 
        <div class="liner">
            <div class="trail"></div>
            <div class="filespace-action-tabset">
                <ul>
                    <li><%= tag("a", {href: "#file-viewer-#{id}"}, true) %>
                        View Files
                    </a></li>
                    <li><%= tag("a", {href: "#file-uploader-#{id}"}, true) %>
                        Upload Files
                    </a></li>
                    <li><%= tag("a", {href: "#file-finder-#{id}"}, true) %>
                        Search Filespace
                    </a></li>
<!-- 
                    <li><%= tag("a", {href: "#user-manager-#{id}"}, true) %>
                        Add or Remove Users
                    </a></li>
                    <li><%= tag("a", {href: "#filespace-manager-#{id}"}, true) %>
                        Share Filespace
                    </a></li>
-->
                </ul>

                <%= tag("div", {id: "file-viewer-#{id}"}, true) %>
                    <%= render(:partial => 'filespaces/viewer',
                      :locals => {filespace: id, root: root,
                        current: current}) %>
                </div>

                <%= tag("div", {id: "file-uploader-#{id}"}, true) %>
                    <%= render(:partial => 'filespaces/uploader',
                      :locals =>  {filespace: id, :root => root,
                        current: current}) %>
                </div>

                <%= tag("div", {id: "file-finder-#{id}"}, true) %>
                    <h2>Search Filespaces Panel</h2>

                    Here we will have a search box that will search over all the
                    file names in all filespaces having the current user as a
                    member. The search results will be displayed as a scrollable
                    list of links that appear to the user as:

                    <div class="path-list">
                        <u>&lt;filespace&gt;:/&lt;folder&gt;/&lt;
                          folder&gt;/.../&lt;file&gt;</u>
                        <br>
                        <u>&lt;filespace&gt;:/&lt;folder&gt;/&lt;
                          folder&gt;/.../&lt;file&gt;</u>
                    </div>

                    When the user clicks on a link, the correct filespace,
                    folder, and file are selected in the <em>View Files</em>
                    panel.  The search does not cover folder names, only file
                    names. If the tab for that filespace is not in the filespace
                    tab bar, it will be added.
                </div>
<!-- 
                <%= tag("div", {id: "user-manager-#{id}"}, true) %>
                    <h1>Add or Remove Users Panel</h1>

                    This tab will only show up for an owner of the filespace.
                    The owner can add any Quosap user as a member of the
                    filespace.  This does not grant any access permissions in
                    itself, it merely makes the new members name appear as a
                    candidate to add to the sharing list of any folder in the
                    filespace.  That is, you can't share a folder to a user is
                    not a member of the filespace.

                </div>

                <%= tag("div", {id: "filespace-manager-#{id}"}, true) %>
                    <h1>Share Filespace Panel</h1>

                    It may be possible to add new owners, editors, or viewers to
                    the filespace as a whole.  We have to work out exactly what
                    these concepts mean.

                </div>
-->
            </div>
        </div>
    </div>
</div>

app/views/filespaces/_form.html.erb
<%= form_for @filespace do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/filespaces/_uploader.html.erb
<!--
  The file uploader Javascript package directly refers to these templates.
  The templating system is jquery-templ, which is "no longer in active
  development or maintenance".
-->

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
                <i class="icon-trash icon-white"></i>
                <span>{%=locale.fileupload.destroy%}</span>
            </button>
            <input type="checkbox" name="delete" value="1">
        </td>
    </tr>
{% } %}
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2">
                <span class="label label-important">
                    {%=locale.fileupload.error%}
                </span>
                {%=locale.fileupload.errors[file.error] || file.error%}
            </td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active">
                    <div class="bar"></div>
                </div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>{%=locale.fileupload.start%}</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>{%=locale.fileupload.cancel%}</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
    
<div class="files-wrapper">
    <div class="liner">

        <%= form_for(Document.new,
          :url => folder_uploads_path(current),
          :html => {:multipart => true,
          :id => "fileupload-form-#{filespace}",
            :class => "fileupload-control"}) do |f| %>
              
            <div class="row fileupload-buttonbar">
                
                <!-- The following button and span must remain as
                      consecutive siblings. -->
                <button type="button" id=<%= "input-#{current}" %>
                    class="file-chooser">
                    <span>Add files...</span>
                </button>
                <span style="display:none;" class="btn fileinput-button">
                    <%= f.file_field :content %>
                </span>
                
                <button type="submit" class="btn start">
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn cancel">
                    <span>Cancel upload</span>
                </button>
            </div>
        
            <div class="fileupload-progress">
                <div class="progress"></div>
            </div>
            
            <!-- The loading indicator is shown during image processing -->
            <div class="fileupload-loading"></div>
            <br>
        
            <!-- The table listing the files available for upload/download -->
            <table class="table table-striped">
                <tbody class="files" data-toggle="modal-gallery"
                  data-target="#modal-gallery">
                </tbody>
            </table>
        <% end %>
    </div>
</div>

<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

app/views/filespaces/_viewer.html.erb
<%= tag("table", {class: "file-table", id: "file-table-#{filespace}",
    data: {filespace: filespace, root: root, folder: current,
      'json-url' => folder_documents_path(current) }}, true)%>
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Uploaded At</th>
            <th>Size</th>
            <th>Content Type</th>
            <th>Checksum</th>
         </tr>
    </thead>
    <tbody>
    </tbody>
</table>

app/views/filespaces/edit.html.erb
<% title "Edit Filespace" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @filespace %>
  <%= link_to "View All", filespaces_path %>
</p>

app/views/filespaces/index.html.erb
<% title "Filespaces" %>

<% for filespace in @filespaces %>
  <div class="filespace">
    <h2><%= link_to filespace.name, filespace %></h2>
  </div>
<% end %>

<p><%= link_to "New Filespace", new_filespace_path %></p>

app/views/filespaces/new.html.erb
<% title "New Folder" %>

<%= render 'form' %>

<p><%= link_to "Back to List", filespaces_path %></p>

app/views/filespaces/show.html.erb
<% title "Filespaces Demo" %>

<%= stylesheet_link_tag "jquery.fileupload-ui" %>
<%= stylesheet_link_tag 'redmond/jquery-ui-1.8.23.custom' %>
<%= stylesheet_link_tag 'jquery.dataTables_themeroller' %>
<%= stylesheet_link_tag 'TableTools' %>
<%= stylesheet_link_tag 'TableTools_JUI' %> 

<script>
    $("body").hide();  // Prevent FOUC
</script>

<div id="content">
    <%= render(partial: 'filespaces/filespace',
        locals: {id: @filespace.id, current: @filespace.current_folder.id,
        root: @filespace.root_folder.id}) %>
</div>

<%= javascript_include_tag 'jquery-ui-1.8.23.custom' %>
<%= javascript_include_tag 'jstree' %>
<%= javascript_include_tag 'datatables' %>
<%= javascript_include_tag 'tabletools' %>

<%= javascript_include_tag 'filespaces/helpers' %>
<%= javascript_include_tag 'filespaces/jstree' %>
<%= javascript_include_tag 'filespaces/datatables' %>
<%= javascript_include_tag 'filespaces/filespace' %>

<%= javascript_include_tag("tmpl.min.js") %>
<%= javascript_include_tag("load-image.min.js") %>
<%= javascript_include_tag("canvas-to-blob.min.js") %>

<%= javascript_include_tag 'fileupload' %>

<script>
    $("body").show(); // prevent FOUC
</script>